export function renderRedemptionPage({ apiBaseUrl, sessionToken }) {
  const api = JSON.stringify(apiBaseUrl);
  const session = JSON.stringify(sessionToken);
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Redeem Membership | Decoy Wallet</title>
  <style>
  :root{--orange:#ff5a00;--ink:#111418;--muted:#65707a}*{box-sizing:border-box}body{margin:0;background:#fff;color:var(--ink);font-family:Arial,sans-serif}main{max-width:520px;min-height:100vh;margin:0 auto;padding:40px 24px 56px}.brand{text-align:center;color:var(--orange);font-weight:900;letter-spacing:.08em}.mark{display:grid;place-items:center;width:104px;height:104px;margin:34px auto 26px;border-radius:50%;background:var(--orange);color:#fff;font-size:50px;box-shadow:0 5px 12px #0002}h1{text-align:center;font-size:34px;line-height:1.08;margin:0 0 14px}p{line-height:1.5;color:var(--muted);text-align:center}label{display:block;font-weight:700;margin:32px 0 8px}input{width:100%;padding:18px;border:3px solid var(--orange);border-radius:8px;font-size:20px;text-align:center;text-transform:uppercase;letter-spacing:.04em;outline:none}input:focus{box-shadow:0 0 0 3px #ff5a0030}button,a.button{display:block;width:100%;margin-top:20px;padding:17px;border:0;border-radius:8px;background:var(--orange);color:#fff;font-size:20px;font-weight:700;text-align:center;text-decoration:none;box-shadow:0 4px 9px #0002}.message{min-height:24px;margin-top:18px;font-weight:700;text-align:center}.error{color:#d90429}.success{color:#069c32}@media(max-height:700px){main{padding-top:24px}.mark{margin-top:22px;width:84px;height:84px}h1{font-size:30px}}</style>
  </head><body><main><div class="brand">DECOY WALLET</div><div class="mark" aria-hidden="true">&#127873;</div><h1>Redeem Membership</h1>
<p>Enter the membership code from your event tag. A valid code adds 365 days of access to your account.</p>
<form id="redeem"><label for="code">Membership code</label><input id="code" autocomplete="off" autocapitalize="characters" placeholder="MWBS-XXXX-XXXX-XXXX" required><button type="submit">Redeem 1 Year</button></form>
<div id="message" class="message" role="status"></div><a id="return" class="button" href="decoywalletapp://paymentreturn" hidden>Return to Decoy Wallet App</a></main>
  <script>const api=${api},session=${session},form=document.getElementById('redeem'),field=document.getElementById('code'),msg=document.getElementById('message'),back=document.getElementById('return');function formatCode(value){const raw=value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,16);if(!raw.startsWith('MWBS'))return raw;const body=raw.slice(4);return ['MWBS',body.slice(0,4),body.slice(4,8),body.slice(8,12)].filter(Boolean).join('-')}field.addEventListener('input',()=>{field.value=formatCode(field.value)});form.addEventListener('submit',async(e)=>{e.preventDefault();msg.className='message';msg.textContent='Redeeming...';try{const response=await fetch(api+'/redeem-membership-code',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({session,code:field.value})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to redeem this code.');msg.className='message success';msg.textContent='Your membership has been extended by 365 days.';form.hidden=true;back.href=data.return_url||back.href;back.hidden=false}catch(error){msg.className='message error';msg.textContent=error.message;}});</script></body></html>`;
}
