alter table public.decoys
  add column if not exists xpub text,
  add column if not exists zpub text,
  add column if not exists watch_public_key text,
  add column if not exists watch_public_key_type text;

comment on column public.decoys.xpub is
  'BIP32 account-level extended public key for the decoy seed, if generated by older clients. Public watch-only metadata; never a seed phrase or private key.';

comment on column public.decoys.zpub is
  'BIP84 account-level extended public key encoded with zpub version bytes for native segwit address monitoring. Public watch-only metadata.';

comment on column public.decoys.watch_public_key is
  'Preferred public watch key used by the decoy seed watcher, usually the BIP84 account zpub. Public watch-only metadata.';

comment on column public.decoys.watch_public_key_type is
  'Descriptor for watch_public_key format, for example bip84-account-zpub.';
